const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      name: 'Adidas Fit shirt',
      slug: 'adidas-adidas-shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      name: 'Nike Slim pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      name: 'Adidas Slim pants',
      slug: 'adidas-slim-pants',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality pants',
    },
  ],
};
export default data;
